name: game_template
description: A mobile game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^4.0.0
  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  logging: ^1.1.0
  provider: ^6.0.2
  get_it: ^7.3.0
  shared_preferences: ^2.0.13
  flutter_svg: ^1.1.6

  firebase_database: ^10.0.6
  firebase_auth: ^4.1.4
  firebase_messaging: ^14.4.1
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3

  games_services: ^3.0.0
  google_mobile_ads: ^2.0.1
  in_app_purchase: ^3.0.1

  connectivity_plus: ^3.0.2
  flutter_keyboard_visibility: ^5.4.0
  flutter_native_splash: ^2.2.16
  url_launcher: ^6.1.10
  package_info_plus: ^3.0.3
  #file_picker: ^5.2.5
  #dropdown_button2: ^2.0.0
  #flutter_local_notifications: ^8.2.0
  #dio: ^4.0.6
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.3.0
  assorted_layout_widgets: ^8.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/chess/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/permanent_marker/permanent_marker_regular.ttf
    - family: Magneto
      fonts:
        - asset: assets/fonts/magneto/magneto.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

analyzer:

